[id='process-instance-migration-installing-service-proc']
= Installing the process instance migration service

You can use the process instance migration (PIM) service to create, export and execute migration plans. The PIM service is provided through a GitHub repository. To install the PIM service, clone the GitHub repository, then run the service and access it in a web browser.

.Prerequisites
* You have defined processes in a backup-ed {PRODUCT} development environment.

.Procedure
. Download the `{PRODUCT_FILE}-add-ons.zip` file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page for {PRODUCT} {PRODUCT_VERSION}.
. Unzip the downloaded archive.
. Move the `{PRODUCT_FILE}-process-migration-service-standalone.jar` file from the add-ons archive to a desired location.
. In the location, create a YAML file containing the {KIE_VERSION} and Quarkus configuration, for example:
+
----
quarkus:
  class-loading:
    removed-artifacts: com.oracle.database.jdbc:ojdbc8,com.ibm.db2:jcc,com.microsoft.sqlserver:mssql-jdbc
  package:
    type: mutable-jar
    user-providers-directory: providers
  http:
    auth:
      basic: true
      policy:
        main-policy:
          roles-allowed: admin
      permission:
        main:
          paths: /*
          policy: main-policy
        public:
          paths: /q/health/*
          policy: permit
          methods: GET
  security:
    users:
      file:
        realm-name: pim_file
        enabled: true
        plain-text: true
        users: users.properties
        roles: roles.properties
    jdbc:
      realm-name: pim_jdbc
      enabled: true
      principal-query:
        sql: SELECT u.password, u.role FROM users u WHERE u.username=?
    ldap:
      realm-name: pim_ldap
      enabled: true
      dir-context:
        url: ldap://override-when-needed
      identity-mapping:
        search-base-dn: ou=users,o=YourCompany,c=ES
# Quartz configuration
  quartz:
    store-type: ram
    start-mode: forced
  resteasy:
    path: /rest
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  hibernate-orm:
    database:
      generation: update
pim:
  auth-method: file
"%int":
  kieservers:
  - host: http://localhost:18080/kie-server/services/rest/server
    username: kieserver
    password: kieserver1!
----
. Start the PIM service:
+
[source,subs="attributes+"]
----
$ java -jar {PRODUCT_FILE}-process-migration-service-standalone.jar -s./config.yml
----
. To re-augment a Quarkus configuration you need to build your application with `quarkus.package.type=mutable-jar`:
+
----
$ mvn clean install -Dquarkus.package.type=mutable-jar
----
. Ensure the `quarkus.launch.rebuild` system property set to `true`:
+
----
java -jar -Dquarkus.launch.rebuild=true -Dquarkus.datasource.db-kind=mariadb -Dquarkus.flyway.sql-migration-prefix=mariadb target/quarkus-app/quarkus-run.jar
----
. After the PIM service is up and running, enter `\http://localhost:8080` in a web browser.
