[id='process-instance-migration-installing-service-proc']
= Installing the process instance migration service

You can use the process instance migration (PIM) service to create, export and execute migration plans. The PIM service is provided through a GitHub repository. To install the PIM service, clone the GitHub repository, then run the service and access it in a web browser.

.Prerequisites
* You have defined processes in a backup-ed {PRODUCT} development environment.
* Java Runtime Environment (JRE) version 11 or later is installed.

.Procedure
. Download the `{PRODUCT_FILE}-add-ons.zip` file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page for {PRODUCT} {PRODUCT_VERSION}.
. Unzip the downloaded archive.
. Move the `{PRODUCT_FILE}-process-migration-service-standalone.jar` file from the add-ons archive to a desired location.
. Start the PIM service:
+
[source,subs="attributes+"]
----
$ java -jar {PRODUCT_FILE}-process-migration-service-standalone.jar -s./config.yml
----
. Ensure the relevant authentication method is set for `auth-method`. Valid values are `file`, `jdbc`, and `ldap`. For example:
+
----
database:
  generation: update
pim:
  auth-method: file
----
. To add dependencies or modify the build time properties by re-augmenting your Quarkus application, build your application with the `quarkus.package.type=mutable-jar` option:
+
----
$ mvn clean install -Dquarkus.package.type=mutable-jar
----
+
For more information about Quarkus application re-augmentation, see https://quarkus.io/guides/reaugmentation[RE-AUGMENT A QUARKUS APPLICATION] guide.
. Ensure the `quarkus.launch.rebuild` system property set to `true`:
+
----
java -jar -Dquarkus.launch.rebuild=true -Dquarkus.datasource.db-kind=mariadb -Dquarkus.flyway.sql-migration-prefix=mariadb target/quarkus-app/quarkus-run.jar
----
. After the PIM service is up and running, enter `\http://localhost:8080` in a web browser.
