[id='installing-and-configuring-smart-router-con']
= Installing and configuring Smart Router

Smart Router ({KIE_SERVER} router) is a lightweight Java component that you can use as an integration layer between multiple {KIE_SERVER}s, client applications, and other components. Depending on your deployment and execution environment, Smart Router can aggregate multiple independent {KIE_SERVER} instances as though they are a single server. Smart Router provides the following features:

Data aggregation::
Collects data from various {KIE_SERVER} instances in a single client request and provides the information to the client application.
+
The router is capable of providing an aggregate sort, however the data returned when used through the management console is in raw format. Therefore, sorting is in whatever way individual servers return. Paging is supported in its standard format.

Routing::
Smart Router is a single endpoint that can receive calls from client applications to any of your services and route each call automatically to the {KIE_SERVER} that runs the specific service.

Load balancing::
Provides efficient load balancing. Load balancing requests for a Smart Router cluster must be managed externally with standard load balancing tools.

Authentication::
Authenticates {KIE_SERVER} instances by using a system property flag and can enable HTTPS traffic.

Environment Management::
Manages the changing environment, for example adding or removing server instances.
