[id='dashbuilder-runtimes-con']
= Dashbuilder runtimes

Dashbuilder Runtime is an add-on application for {PRODUCT} that you can use to run dashboards in standalone installations. Dashbuilder Runtime is available as a WAR file that you can run on {EAP}. To use Dashbuilder Runtime, you first author dashboards in {CENTRAL}, export the assets from {CENTRAL}, and run them on a web application without requiring to use {CENTRAL} for business metrics.

Users with access to Dashbuilder Runtime are able to import the assets and explore the dashboards without using {CENTRAL}. If no static dashboards are configured then Dashbuilder Runtime prompts the user to upload a dashboard. When the dashboard is uploaded the runtime will only use that dashboard until the runtime is restarted.

The navigation between pages is the same as the configuration in Business Central. This means that if page 1 is in group1 and page 2 is in group2, then the same group will be imported and will remain as the navigation in Runtime. A page is added to a group called “Dashboards”.
