[id='managing-business-central-editing-users-proc']
= Editing users

Change the group and role of a user from the *Users* option in *Settings*. All user permissions are based on the group and role permissions of the user. You can view the user permissions from the *Permissions* tab.

.Procedure
. In {CENTRAL}, go to *Admin* -> *Users*.
. From the *All users* list, click the user you want to edit. The user details display in the right pane.
. Click *Edit* to perform any of the following tasks:
* To change the groups of a user:
.. In the *Groups* tab, click *Add to groups*. The *Group selection for user* window opens.
.. Select the groups you want the user to be a part of.
.. Click *Add to selected groups*.
.. Click *Save* to apply changes.
* To change the roles of a user:
.. From *Roles* tab, click *Add roles*. The *Role selection for user* window opens.
.. Select the roles you want to assign to the user.
.. Click *Add to selected roles*.
.. Click *Save* to apply changes.
* To view user permissions:
.. Click the *Permissions* tab and expand the attributes to view user permissions.
.. Click *Save* to apply changes.
* To change the password of a user:
.. Click *Change Password*. The *Change password for user* window opens.
.. Enter and confirm the new password and click *Change*.
.. Click *Save* to apply changes.
* To delete the user:
.. Click *Delete*.
.. Click *Yes* to confirm removal of the user.
