[id='managing-business-central-configuring-git-hooks-existing-remote-repository-proc-{context}']
= Configuring Git hooks for an existing remote Git project repository

You can create a post-commit Git hook in a remote Git repository of an existing project and integrate the repository with {CENTRAL}.

.Prerequisites
* {PRODUCT} is installed in a {EAP} {EAP_VERSION} server instance.
* Read access credentials for the external Git repository.
* Post-commit Git hook is prepared.
* (For Windows operating system) Cygwin is installed with the Git package added during installation and the path to the Cygwin `/bin` folder is added to your environment `PATH` variable. For example, `C:\cygwin64\bin`. For more information about Cygwin installation, see http://www.cygwin.com/install.html[Installing and Updating Cygwin Packages].

.Procedure
. In a command terminal, navigate to the `hooks` folder located in the repository Git folder of the project. For example:
+
[source]
----
$ cd _EAP_HOME_/bin/.niogit/<SPACE>/<PROJECT_NAME>.git/hooks
----
. Create a `post-commit` file that pushes changes to the remote Git repository. For more information about creating post-commit Git hooks, see <<managing-business-central-creating-git-hooks-proc-configuring-central>>.
. Optional: To check that the configuration was successful, create a guided rule in {CENTRAL}:

.. In {CENTRAL} go to *Menu* -> *Projects* -> *Add Asset* -> *Guided Rule*.
.. On the *Create new Guided Rule* page, enter the required information.
.. Click *Ok*.
+
{CENTRAL} automatically pushes all changes to the remote repository.
